---
editor_options:
  markdown:
    wrap: 72
output:
  html_document:
    df_print: paged
---

```{r}

library(dplyr)
library(maps)
library(spdep)
library(MASS)
library(INLA)


```

```{r}
# load data

load("Agrimonia_Dataset_v_3_0_0.Rdata")

df <- AgrImOnIA_Dataset_v_3_0_0

```

```{r}

# create area_id column for spatial component (latent random effect)


# visualize the locations of our data
unique_locs <- unique(df[, c("Latitude", "Longitude")])

plot(unique_locs$Longitude, unique_locs$Latitude,
     pch = 19, col = "steelblue",
     xlab = "Longitude", ylab = "Latitude",
     main = "Monitoring Station Locations") # the stations look pretty uniformly spread across the sampling area

map("world", region = "Italy", add = TRUE, col = "grey80")
points(unique_locs$Longitude, unique_locs$Latitude, pch = 19, col = "steelblue")

# create area_id column to use as spatial random effect
df$area_id <- as.integer(factor(paste(df$Latitude,df$Longitude,sep = "_")))


# Q from Zac: why is this an integer rather than a factor? I guess it probably doesn't make a difference once it's random effect?

```

```{r}

# define a t_id temporal "season" to asses seasonal patterns (latent random effect)

# try using "month-year" as the seasonal t_id, so that we have a unique id for each month and year combination (RW1 might be good here instead of RW2 bc may be more sharp monthly changes)

df$t_id <- as.integer(factor(format(df$Time, "%Y-%m")))


```

```{r}
# create nearest neighbors graph to ensure INLA can identify locations closer to eachother

# get unique locations ordered by area_id
unique_locs <- unique(df[order(df$area_id), 
                                       c("area_id", "Latitude", "Longitude")])

# build kNN neighbourhood graph
coords <- as.matrix(unique_locs[, c("Longitude", "Latitude")])
nb <- knn2nb(knearneigh(coords, k = 5))

# write and read INLA graph
nb2INLA("stations.graph", nb)
g <- inla.read.graph("stations.graph")


# Qs from Zac: What/why are you doing here? what is nearest neighbours doing? Is this some kind of alternative to fmesher, creating a mesh?
```

```{## Zac's attempt - using inlabru}

statdomain <- inla.nonconvex.hull(as.matrix(unique_locs[, 2:1]),
  convex = -0.05, concave = -0.1,
  resolution = c(100, 100))
plot(statdomain)

statmesh <- fmesher::fm_mesh_2d(boundary = statdomain,
  max.edge = c(2, 2), cutoff = 0.2)
plot(statmesh)
points(unique_locs[,2:1], col="red", pch=20)
```

\`\`\`

```{r}
library(inlabru)
library(sf)

Locations = data.frame(easting=df$Longitude, northing=df$Latitude) 

loc.spde = inla.spde2.pcmatern(mesh = statmesh,
           prior.range = c(1, 0.5), 
           prior.sigma = c(200, 0.1),constr=TRUE) 


df$geometry <- sf::st_as_sf(Locations, coords = c("easting", "northing"))$geometry
cmp <- AQ_pm25 ~ floc(geometry, model = loc.spde)+ Altitude+ Intercept(1)

q2.m2.bru <- bru(components=cmp, family = "gaussian",data=df)
summary(q2.m2.bru)

## r markdown won't work for some reason. This might work though.
```

```{r}

# investigate target variable of interest, PM2.5 concentrations (AQ_pm25 -> air quality pm 2.5)

summary(df$AQ_pm25) # lots of missing PM2.5 values
sum(df$AQ_pm25 == 0, na.rm = TRUE) # a few 0 values (also imply missing as 0 concentraiton is basically impossible)

# turn 0s into NaNs
df$AQ_pm25[df$AQ_pm25 == 0] <- NaN
# remove NaNs (and 0s) to analyse distribution of PM2.5
complete_case_df <- df[!is.na(df$AQ_pm25), ]
# note: can keep NaNs in modeling bc inla still works, but discludes NaNs in likelihood calculation but still outputs posterior predictions for them which may be useful

# raw
hist(complete_case_df$AQ_pm25, freq = FALSE, main = "Raw")

# log transformed
hist(log(complete_case_df$AQ_pm25), breaks=100, freq = FALSE, main = "Log")

# square root transformed (suggests gamma)
hist(sqrt(complete_case_df$AQ_pm25), freq = FALSE, main = "Square Root")

# try fitting with log-normal and gamma

# fit both distributions
fit_gamma <- fitdistr(complete_case_df$AQ_pm25, "gamma")
shape    <- fit_gamma$estimate["shape"]
rate     <- fit_gamma$estimate["rate"]

fit_lnorm <- fitdistr(complete_case_df$AQ_pm25, "lognormal")
meanlog   <- fit_lnorm$estimate["meanlog"]
sdlog     <- fit_lnorm$estimate["sdlog"]

# plot histogram
hist(complete_case_df$AQ_pm25, freq = FALSE,
     main = "PM2.5 with Gamma and Log-Normal Overlay",
     xlab = "PM2.5 Concentration",
     col = "lightblue", border = "white",
     ylim = c(0, 0.05))

# overlay both density lines
x_seq <- seq(0, max(complete_case_df$AQ_pm25), length.out = 500)
lines(x_seq, dgamma(x_seq, shape = shape, rate = rate),
      col = "red", lwd = 2)
lines(x_seq, dlnorm(x_seq, meanlog = meanlog, sdlog = sdlog),
      col = "darkgreen", lwd = 2)

legend("topright", 
       legend = c("Observed", "Gamma", "Log-Normal"),
       fill   = c("lightblue", NA, NA),
       lty    = c(NA, 1, 1),
       col    = c("lightblue", "red", "darkgreen"),
       lwd    = c(NA, 2, 2))


# evaluate fit with AIC
AIC(fit_gamma)
AIC(fit_lnorm)

# go with gamma (lower AIC and better visual fit)

```

```{r}
# try fitting bayesian spatio-temporal models with altitude as the covariate

# scale the covariate (altitude)
df$Altitude_sc <- as.numeric(scale(df$Altitude))


ctrl_pred <- list(compute = TRUE, link = 1)

ctrl_comp <- list(
  dic = TRUE,
  waic = TRUE,
  cpo = FALSE,
  config=TRUE
)

inla.setOption(num.threads = 8)

# M0: fixed effects only (no spatial/temporal structure)
m0 <- inla(
  AQ_pm25 ~ 1 + Altitude_sc,
  data = df,
  family = "gamma",
  control.predictor = ctrl_pred,
  control.compute = ctrl_comp
)

# M1: + temporal RW1 trend
m1 <- inla(
  AQ_pm25 ~ 1 + Altitude_sc +
    f(t_id, model = "rw1", constr = TRUE),
  data = df,
  family = "gamma",
  control.predictor = ctrl_pred,
  control.compute = ctrl_comp
)


# M2: + spatial BYM2 effect
m2 <- inla(
  AQ_pm25 ~ 1 + Altitude_sc +
    f(area_id, model = "bym2", graph = g,
      scale.model = TRUE, constr = TRUE),
  data = df,
  family = "gamma",
  control.predictor = ctrl_pred,
  control.compute = ctrl_comp
)

# M3: full spatio-temporal model
m3 <- inla(
  AQ_pm25 ~ 1 + Altitude_sc +
    f(t_id, model = "rw1", constr = TRUE) +
    f(area_id, model = "bym2", graph = g,
      scale.model = TRUE, constr = TRUE),
  data = df,
  family = "gamma",
  control.predictor = ctrl_pred,
  control.compute = ctrl_comp
)



```

```{r}
# evaluate fits using WAIC

cat("M0 WAIC =",  m0$waic$waic, "\n")
cat("M1 WAIC =",  m1$waic$waic, "\n")
cat("M2 WAIC =",  m2$waic$waic, "\n")
cat("M3 WAIC =",  m3$waic$waic)



```
